// This file defines the layout for your application. 
// It wraps around your pages and can include common elements like headers, footers, and styles.

import type { Metadata } from "next"
// import { Inter } from "next/font/google"
import "../styles/globals.css"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

import Nav from "../components/Nav"

// const inter = Inter({ subsets: ["latin"] })

// HTML Meta Tags
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body> {/* className={inter.className} */}

        <div className="mx-6 md:max-w-2xl md:mx-auto">
          <Nav />

          <main>{children}</main>          

          <ToastContainer limit={1} position="top-right" autoClose={5000} />
        </div>


      </body>
    </html>
  )
}
